apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  strategy:
      type: RollingUpdate
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-container
          image: jasonbigcow/dcard-advertisement-api-api:latest
          imagePullPolicy: Always
          command: ["./api"]
          args: ["-config","kubernetes"]
          volumeMounts:
          - name: api-scheduler-config-volume
            mountPath: /app/.env
          # https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#populate-a-volume-with-data-stored-in-a-configmap
          ports:
            - containerPort: 8080
          # resources:
          #   requests:
          #     memory: "64Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
      volumes:
      - name: api-scheduler-config-volume
        configMap:
          name: api-scheduler-config 
