apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-deployment
  labels:
    app: scheduler
spec:
  replicas: 1
  strategy:
      type: RollingUpdate
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
        - name: scheduler-container
          image: jasonbigcow/dcard-advertisement-api-scheduler:latest
          imagePullPolicy: Always
          command: ["./scheduler"]
          args: ["-config","kubernetes"]
          # resources:
          #   requests:
          #     memory: "64Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
      volumes:
        - name: api-scheduler-config-volume
          configMap:
            name: api-scheduler-config
            items:
              - key: kubernetes.yaml
                path: .env/kubernetes.yaml
