# k6-resource.yml

apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-sample
spec:
  parallelism: 4
  script:
    configMap:
      name: k6-script-config
      file: load-test.js
  separate: false
  runner:
    image: jasonbigcow/dcard-advertisement-api-k6-runner:latest
    imagePullPolicy: Always
    env: 
      - name: API_HOST
        valueFrom:
          configMapKeyRef:
            name: k6-config
            key: API_HOST
      - name: API_PORT
        valueFrom:
          configMapKeyRef:
            name: k6-config
            key: API_PORT
      - name: AGE_START
        valueFrom:
          configMapKeyRef:
            name: k6-config
            key: AGE_START
      - name: AGE_END
        valueFrom:
          configMapKeyRef:
            name: k6-config
            key: AGE_END
    metadata:
      # labels:
      #   cool-label: foo
      # annotations:
      #   cool-annotation: bar
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
    resources:
      limits:
        cpu: 200m
        memory: 1000Mi
      requests:
        cpu: 100m
        memory: 500Mi
  starter:
    image: jasonbigcow/dcard-advertisement-api-k6-starter:latest  
    imagePullPolicy: Always 
    metadata:
      # labels:
      #   cool-label: foo
      # annotations:
      #   cool-annotation: bar
    securityContext:
      runAsUser: 2000
      runAsGroup: 2000
      runAsNonRoot: true