apiVersion: v1
kind: Pod
metadata:
  name: generator-pod
  labels:
    app: generator
spec:
  containers:
    - name: generator-container
      image: jasonbigcow/dcard-advertisement-api-generator:latest
      imagePullPolicy: Always
      command: ["./generator"]
      args: ["-config","kubernetes"]
      volumeMounts:
        - name: api-scheduler-config-volume
          mountPath: /app/.env
       # resources:
    #   requests:
    #     memory: "64Mi"
    #     cpu: "250m"
    #   limits:
    #     memory: "128Mi"
    #     cpu: "500m"
  restartPolicy: Never
  volumes:
    - name: api-scheduler-config-volume
      configMap:
        name: api-scheduler-config 
