definitions:
  github_com_jason810496_Dcard-Advertisement-API_pkg_schemas.CreateAdConditions:
    properties:
      ageEnd:
        example: 30
        maximum: 100
        minimum: 1
        type: integer
      ageStart:
        example: 18
        maximum: 100
        minimum: 1
        type: integer
      country:
        example:
        - TW
        - JP
        items:
          type: string
        type: array
      platform:
        example:
        - ios
        - android
        items:
          type: string
        type: array
    required:
    - ageEnd
    - ageStart
    - country
    - platform
    type: object
  github_com_jason810496_Dcard-Advertisement-API_pkg_schemas.CreateAdRequest:
    properties:
      conditions:
        $ref: '#/definitions/github_com_jason810496_Dcard-Advertisement-API_pkg_schemas.CreateAdConditions'
      endAt:
        example: "2023-12-31T16:00:00.000Z"
        type: string
      startAt:
        example: "2023-12-10T03:00:00.000Z"
        type: string
      title:
        example: AD 123
        type: string
    required:
    - conditions
    - endAt
    - startAt
    - title
    type: object
  github_com_jason810496_Dcard-Advertisement-API_pkg_schemas.CreateAdResponse:
    properties:
      message:
        example: create success
        type: string
    type: object
  github_com_jason810496_Dcard-Advertisement-API_pkg_schemas.PublicAdItem:
    properties:
      endAt:
        example: "2021-12-31 23:59:59"
        type: string
      title:
        example: This is an AD title
        type: string
    type: object
  github_com_jason810496_Dcard-Advertisement-API_pkg_schemas.PublicAdResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/github_com_jason810496_Dcard-Advertisement-API_pkg_schemas.PublicAdItem'
        type: array
    type: object
  github_com_jason810496_Dcard-Advertisement-API_pkg_utils.ErrorMsg:
    properties:
      field:
        type: string
      message:
        example: bad request
        type: string
    type: object
  github_com_jason810496_Dcard-Advertisement-API_pkg_utils.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      errors:
        items:
          $ref: '#/definitions/github_com_jason810496_Dcard-Advertisement-API_pkg_utils.ErrorMsg'
        type: array
    type: object
host: 0.0.0.0:8080
info:
  contact: {}
  description: This is a swagger for Dcard Backend Intern 2024
  title: Dcard Advertisement API
  version: "1.0"
paths:
  /api/v1/ad:
    get:
      description: query ad by query parameters age, country
      parameters:
      - description: age
        in: query
        maximum: 100
        minimum: 1
        name: age
        type: integer
      - description: country
        enum:
        - TW
        - HK
        - JP
        - US
        - KR
        in: query
        name: country
        type: string
      - description: platform
        enum:
        - ios
        - android
        - web
        in: query
        name: platform
        type: string
      - description: gender
        enum:
        - F
        - M
        in: query
        name: gender
        type: string
      - description: limit
        in: query
        name: limit
        type: integer
      - description: offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_jason810496_Dcard-Advertisement-API_pkg_schemas.PublicAdResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_jason810496_Dcard-Advertisement-API_pkg_utils.HTTPError'
      summary: public API
      tags:
      - ad
    post:
      consumes:
      - application/json
      description: create advertisement with `startAt`, `endAt` and `condition`
      parameters:
      - description: advertisement request schema
        in: body
        name: advertisement
        required: true
        schema:
          $ref: '#/definitions/github_com_jason810496_Dcard-Advertisement-API_pkg_schemas.CreateAdRequest'
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_jason810496_Dcard-Advertisement-API_pkg_schemas.CreateAdResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_jason810496_Dcard-Advertisement-API_pkg_utils.HTTPError'
      summary: admin API
      tags:
      - ad
schemes:
- http,
- https
swagger: "2.0"
