apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-statefulset
spec:
  serviceName: postgresql
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:15.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "100m"
          volumeMounts:
            - name: postgresql-pvc
              mountPath: /var/lib/postgresql/data
              subPath: postgresql
              # https://devpress.csdn.net/k8s/62fff0cbc6770329308067d0.html
              # https://devopswithkubernetes.com/part-3/1-introduction-to-gke#persisting-data-in-gke
  volumeClaimTemplates:
    - metadata:
        name: postgresql-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        # https://www.googlecloudcommunity.com/gc/Google-Kubernetes-Engine-GKE/How-to-utilize-filestore-as-persistent-volume-in-statefulset-gke/m-p/618872
        # https://cloud.google.com/filestore/docs/csi-driver#storage-class
        storageClassName: "standard"
        resources:
          requests:
            storage: 3Gi