name: Run k6 load test on GitHub Actions with Docker Compose

on:
  push:
    branches:
    - benchmark/**
    - release/v2
  pull_request:
    branches:
    - benchmark/**
    - release/v2

jobs:
  docker:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Config file and Environment Variables
      run: |
        cp .env/test.template.yaml .env/test.yaml
        cp .env/dev/db.template.env .env/dev/db.env
        cp .env/dev/redis.template.env .env/dev/redis.env
        cp .env/dev/k6.template.env .env/dev/k6.env

    - name: Try fix Redis issue
      run: |
        sudo sysctl vm.overcommit_memory=1
        sudo sysctl -w net.core.somaxconn=65535

    - name: Check Config 
      run: |
        ls -l .env
        ls -l .env/dev

    - name: Start DB,redis
      run: |
        docker compose -f "docker-compose-benchmark.yaml" up db redis -d
        sudo chmod 777 -R ./stateful_volumes
        sleep 3
        docker compose -f "docker-compose-benchmark.yaml" logs db
        docker compose -f "docker-compose-benchmark.yaml" logs redis

    - name: check Docker
      run: docker compose -f "docker-compose-benchmark.yaml" ps -a

    - name: Generate data
      run: docker compose -f "docker-compose-benchmark.yaml" run -v $PWD/.env:/app/.env --rm -d generator

    - name: Start Scheduler
      run: |
        docker compose -f "docker-compose-benchmark.yaml" run -v $PWD/.env:/app/.env -d scheduler
        sleep 2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: install go modules
      run: go mod download

    - name: Build API
      run: go build -v -w -o bin/api ./cmd/api 

    - name: Start API at Background
      run: ./bin/api -config test &

    - name: Download k6 
      run: |
        sudo gpg -k
        sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
        echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        sudo apt-get update
        sudo apt-get install k6
        k6 version

    - name: Run k6 test
      run: |
        k6 run -e API_HOST=127.0.0.1 -e API_PORT=8080 -e DURATION=1m -e AGE_START=18 -e AGE_END=35 k6/load-test.js

    - name: Stop containers
      if: always()
      run: docker compose -f "docker-compose-benchmark.yaml" down