name: Run k6 load test on GitHub Actions with Docker Compose

on:
  push:
    branches:
    - benchmark/**
    - release/v2
  pull_request:
    branches:
    - benchmark/**
    - release/v2

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Config file and Environment Variables
      run: |
        cp .env/test.template.yaml .env/test.yaml
        cp .env/dev/db.template.env .env/dev/db.env
        cp .env/dev/redis.template.env .env/dev/redis.env
        cp .env/dev/k6.template.env .env/dev/k6.env

    - name: Try fix Redis issue
      run: |
        sudo sysctl vm.overcommit_memory=1
        sudo sysctl -w net.core.somaxconn=65535

    - name: Check Config 
      run: |
        ls -l .env
        ls -l .env/dev

    - name: Start DB,redis
      run: |
        docker compose -f "docker-compose-benchmark.yaml" up db redis -d
        sudo chmod 777 -R ./stateful_volumes
        sleep 3
        docker compose -f "docker-compose-benchmark.yaml" logs db
        docker compose -f "docker-compose-benchmark.yaml" logs redis

    - name: check Docker
      run: docker compose -f "docker-compose-benchmark.yaml" ps -a

    - name: Generate data
      run: docker compose -f "docker-compose-benchmark.yaml" run -v $PWD/.env:/app/.env --rm generator

    - name: Start Scheduler
      run: |
        docker compose -f "docker-compose-benchmark.yaml" run -v $PWD/.env:/app/.env -d scheduler
        sleep 2


    - name: Start API
      run: docker compose -f "docker-compose-benchmark.yaml" run -v $PWD/.env:/app/.env -d api

    - name: Run k6 load test
      run: docker compose run -v $PWD/k6/:/k6 k6 run /k6/load-test.js

    - name: Stop containers
      if: always()
      run: docker compose -f "docker-compose-benchmark.yaml" down