name: Build Scheduler Image

on:
    # push:
    #     branches: [main, release/*]
    # pull_request:
    #     branches: [main, release/*]
    push:
        branches: [build]
    pull_request:
        branches: [build]
env:
    IMAGE_NAME: dcard-advertisement-api-scheduler
    DOCKERFILE_PATH: ./deployments/dev/scheduler/Dockerfile
    BUILD_CONTEXT: .
    IMAGE_TAG: v2
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Set up containerd
              uses: crazy-max/ghaction-setup-containerd@v3
            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build Docker image
              uses: docker/build-push-action@v4
              with:
                context: ${{ env.BUILD_CONTEXT }}
                file: ${{ env.DOCKERFILE_PATH }}
                platforms: linux/amd64,linux/arm64
                tags: docker.io/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
                outputs: type=oci,dest=/tmp/image.tar
                cache-from: type=gha
                cache-to: type=gha,mode=max
            - name: Import image in containerd
              run: |
                sudo ctr i import --base-name docker.io/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} --digests --all-platforms /tmp/image.tar
            - name: Push image to containerd
              run: |
                sudo ctr i push --user "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}" docker.io/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}